version: '2'
services:
  nginx:
    image: nginx:1.13
    hostname: nginx
    volumes:
      - ./etc:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./nginx-log:/var/log/nginx
    ports:
      - "17080:443"
  apache:
    image: httpd:2.4
    hostname: apache
    ports:
     - "8090:80"
