version: '2'
services:
  nginx:
    image: nginx:1.13
    hostname: nginx
    volumes:
      - ./etc:/etc/nginx/conf.d
      - ./certs:/etc/nginx/web-ca-chain.pem
      - ./certs:/etc/nginx/web.key
    ports:
      - "80:80"
  apache:
    image: httpd:2.4
    hostname: apache
    ports:
     - "8090:80"
