version: '2'
services:
  nginx:
    image: ${NGINX_IMAGE}
    hostname: nginx
    volumes:
      - ./etc:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ${NGINX_LOG_DIR}:/var/log/nginx
    ports:
      - "${NGINX_PORT}:443"
  apache:
    image: ${APACHE_IMAGE}
    hostname: apache
    ports:
     - "8090:80"
